python scripts/run_train.py \
    --name="lc_best0" \
    --config=config.yaml \
    --train_file=train.xyz \
    --valid_fraction=0.2 \
    --test_file=train.xyz \
    --E0s=fix \
    --model=LocalCharges \
    --weight_decay=1e-8 \
    --ema \
    --ema_decay=0.99999 \
    --clip_grad=100 \
    --batch_size=16 \
    --valid_batch_size=32 \
    --eval_interval=1 \
    --patience=40 \
    --error_table=PerAtomRMSE \
    --device=cuda \
    --default_dtype=float64 \
    --seed=1 \
    --keep_checkpoints \
    --save_all_checkpoints \
    --restart_latest \
    --num_workers=4 \
    --save_cpu
